
- name: Install required packages for forklift (RHEL 9)
  ansible.builtin.package:
    name:
      - git
      - ansible-core
      - qemu-kvm
      - qemu-img
      - vagrant
    state: present
  become: true

- name: Clone the forklift repository
  ansible.builtin.git:
    repo: https://github.com/theforeman/forklift
    dest: /home/vagrant/forklift
    version: HEAD
    update: yes
    force: yes
  become_user: vagrant

