- name: Enable CodeReady Builder repository for RHEL 9
  ansible.builtin.command: subscription-manager repos --enable codeready-builder-for-rhel-9-{{ ansible_architecture }}-rpms
  become: true

- name: Install required packages for forklift (RHEL 9)
  ansible.builtin.package:
    name:
      - git
      - ansible-core
      - qemu-kvm
      - qemu-img
      - vagrant
      - libvirt
      - g++
      - ruby-devel
      - libvirt-devel
    state: present
  become: true

- name: Clone the forklift repository
  ansible.builtin.git:
    repo: https://github.com/theforeman/forklift
    dest: /home/vagrant/forklift
    version: HEAD
    update: yes
    force: yes
  become_user: vagrant

- name: Install vagrant-hostmanager plugin
  ansible.builtin.command:
    cmd: vagrant plugin install hostmanager
    chdir: /home/vagrant/forklift/
  become_user: vagrant

- name: Install forklift dependencies with ansible-galaxy
  ansible.builtin.command:
    cmd: ansible-galaxy collection install -r requirements.yml
    chdir: /home/vagrant/forklift/
  become_user: vagrant
